-- ================================================================
-- MIGRATION INCRÉMENTALE — 29 septembre 2026 (partie B)
-- ================================================================
-- Complète migration_2026-09-29.sql : équilibre la répartition des
-- exercices par catégorie/niveau (chaque case avait parfois aussi peu
-- qu'1 exercice, ex. Thèmes/facile en avait 0). Ajoute 34 exercices
-- pour amener chaque case à au moins 6, en réutilisant uniquement des
-- formes de contenu JSON déjà supportées par genererQuestions()
-- (ExercicePartenaire.tsx) — aucun changement de code nécessaire.
--
-- Avant de lancer :
--   1. Sauvegarde (mysqldump).
--   2. Vérifier qu'aucun exercice d'id 96 à 129 n'existe déjà
--      (SELECT id FROM Exercices WHERE id BETWEEN 96 AND 129;).
--   3. Ne PAS relancer ce fichier une seconde fois tel quel.
-- ================================================================

INSERT INTO `Exercices` (`id`, `titre`, `niveau`, `description`, `audio_url`, `categorie_id`, `type_exercice`, `contenu`) VALUES
(96,'Complétez la phrase (à la maison)','facile','Écoutez la phrase entière et identifiez le mot manquant, dans un contexte très simple.','',6,'comprendre','{"phrases": [{"phrase": "Il fait froid, je mets mon ......", "alternatives": ["manteau", "chapeau", "pull"]}, {"phrase": "J\'ai soif, je bois un verre d\'......", "alternatives": ["eau", "pain", "chaise"]}, {"phrase": "Le soir, je me couche dans mon ......", "alternatives": ["lit", "jardin", "garage"]}, {"phrase": "Pour couper le pain, j\'utilise un ......", "alternatives": ["couteau", "peigne", "stylo"]}, {"phrase": "Le matin, je me lave les ......", "alternatives": ["dents", "cheveux", "mains"]}], "instructions": "Votre partenaire lit la phrase entière. Identifiez le mot manquant parmi les choix.", "consigne_partenaire": "Lisez la phrase complète naturellement, en insérant l\'un des mots proposés."}'),
(97,'Qui fait quoi ?','facile','Écoutez une phrase simple sur un métier et dites si vous avez bien compris.','',6,'comprendre','{"theme": "Les métiers", "phrases": [{"texte": "Le facteur apporte le courrier chaque matin.", "mot_cle": "facteur"}, {"texte": "Le boulanger fait cuire le pain très tôt.", "mot_cle": "boulanger"}, {"texte": "Le jardinier arrose les fleurs tous les jours.", "mot_cle": "jardinier"}, {"texte": "Le pompier éteint les incendies.", "mot_cle": "pompier"}, {"texte": "Le médecin examine ses patients toute la journée.", "mot_cle": "médecin"}], "instructions": "Votre partenaire lit une phrase simple sur un métier. Dites si vous avez bien compris de qui elle parle.", "consigne_partenaire": "Lisez chaque phrase clairement, une seule fois."}'),
(98,'Complétez la phrase (la nourriture)','facile','Écoutez la phrase entière et identifiez le mot manquant, thème nourriture.','',6,'comprendre','{"phrases": [{"phrase": "Le matin, je mange souvent des ......", "alternatives": ["céréales", "chaussures", "livres"]}, {"phrase": "Pour le dessert, elle a pris une ......", "alternatives": ["glace", "valise", "lampe"]}, {"phrase": "J\'ajoute du sel et du ...... dans la soupe.", "alternatives": ["poivre", "papier", "savon"]}, {"phrase": "Il boit son café avec un peu de ......", "alternatives": ["lait", "sable", "carton"]}, {"phrase": "Elle coupe la pomme avec un ......", "alternatives": ["couteau", "marteau", "peigne"]}], "instructions": "Votre partenaire lit la phrase entière. Identifiez le mot manquant parmi les choix.", "consigne_partenaire": "Lisez la phrase complète naturellement, en insérant l\'un des mots proposés."}'),
(99,'Une situation simple (la météo)','facile','Écoutez une phrase simple sur la météo et dites si vous avez bien compris.','',6,'comprendre','{"theme": "La météo", "phrases": [{"texte": "Il pleut, alors elle prend son parapluie.", "mot_cle": "parapluie"}, {"texte": "Il fait très chaud, il ouvre la fenêtre.", "mot_cle": "fenêtre"}, {"texte": "Il neige, les enfants sont contents.", "mot_cle": "neige"}, {"texte": "Le vent souffle fort sur la plage.", "mot_cle": "vent"}, {"texte": "Le soleil brille, on part se promener.", "mot_cle": "soleil"}], "instructions": "Votre partenaire lit une phrase simple sur la météo. Dites si vous avez bien compris.", "consigne_partenaire": "Lisez chaque phrase clairement, une seule fois."}'),
(100,'Complétez la phrase (les vêtements)','facile','Écoutez la phrase entière et identifiez le mot manquant, thème vêtements.','',6,'comprendre','{"phrases": [{"phrase": "Pour aller courir, je mets mes ......", "alternatives": ["baskets", "sandales", "bottes"]}, {"phrase": "Quand il pleut, je porte des ......", "alternatives": ["bottes", "tongs", "chaussons"]}, {"phrase": "Elle a acheté une nouvelle ...... pour l\'hiver.", "alternatives": ["écharpe", "assiette", "brosse"]}, {"phrase": "Il enfile ses ...... avant de sortir.", "alternatives": ["chaussures", "lunettes", "gants"]}, {"phrase": "Elle range son ...... dans l\'armoire.", "alternatives": ["manteau", "vélo", "téléphone"]}], "instructions": "Votre partenaire lit la phrase entière. Identifiez le mot manquant parmi les choix.", "consigne_partenaire": "Lisez la phrase complète naturellement, en insérant l\'un des mots proposés."}'),
(101,'Questions sur vos habitudes','moyen','Votre partenaire vous pose des questions sur vos habitudes quotidiennes.','',6,'comprendre','{"groupes": [{"contexte": "Vos habitudes du matin", "questions": ["Que faites-vous en premier le matin ?", "Prenez-vous un petit-déjeuner copieux ?", "Combien de temps mettez-vous à vous préparer ?"]}, {"contexte": "Vos habitudes du soir", "questions": ["À quelle heure vous couchez-vous en général ?", "Lisez-vous avant de dormir ?", "Regardez-vous la télévision le soir ?"]}], "instructions": "Votre partenaire vous pose des questions sur vos habitudes. Répondez naturellement.", "consigne_partenaire": "Annoncez le sous-thème, puis posez les questions une par une."}'),
(102,'Repérage express','difficile','Cliquez chaque fois que vous entendez un son. Les sons sont plus rapprochés et plus nombreux qu\'en niveau moyen.','',3,'detecter',NULL),
(103,'Repérer un signal isolé','difficile','Cliquez chaque fois que vous entendez un son, avec un bruit de fond présent en continu.','',3,'detecter',NULL),
(104,'Compter les syllabes (mots longs)','difficile','Écoutez le mot et comptez le nombre de syllabes prononcées.','',3,'detecter','{"syllabes": [{"mot": "ordinateur", "nb": 5}, {"mot": "anniversaire", "nb": 5}, {"mot": "réfrigérateur", "nb": 5}, {"mot": "extraordinaire", "nb": 5}, {"mot": "téléphone", "nb": 3}, {"mot": "bibliothèque", "nb": 4}], "instructions": "Écoutez et déterminez le nombre de syllabes du mot.", "consigne_partenaire": "Prononcez chaque mot clairement, en détachant légèrement les syllabes."}'),
(105,'Mot très court ou très long ?','difficile','Écoutez et déterminez si le mot est très court ou très long — la différence est plus subtile qu\'en facile.','',3,'detecter','{"mots": [{"mot": "clé", "type": "court"}, {"mot": "constitutionnellement", "type": "long"}, {"mot": "feu", "type": "court"}, {"mot": "incompréhensible", "type": "long"}, {"mot": "roi", "type": "court"}, {"mot": "anticonstitutionnel", "type": "long"}, {"mot": "eau", "type": "court"}, {"mot": "réfrigérateur", "type": "long"}], "instructions": "Écoutez et déterminez si le mot est court ou long.", "consigne_partenaire": "Prononcez chaque mot à vitesse normale, sans exagérer sa durée."}'),
(106,'Voyelles nasales : an, on, in','difficile','Distinguez les trois voyelles nasales du français, souvent confondues.','',5,'distinguer','{"principe": "Contraste des voyelles nasales : an/on/in", "triplets": [{"mots": ["banc", "bon", "bain"]}, {"mots": ["temps", "thon", "teint"]}, {"mots": ["grand", "rond", "rein"]}, {"mots": ["dans", "dont", "daim"]}, {"mots": ["gant", "gond", "gain"]}, {"mots": ["vent", "vont", "vin"]}], "instructions": "Votre partenaire choisit et prononce un mot parmi les trois proposés. Identifiez lequel.", "consigne_partenaire": "Pour chaque triplet, choisissez un mot au hasard et prononcez-le naturellement."}'),
(107,'Consonnes liquides : [l] contre [r]','difficile','Distinguez [l] et [r], un contraste fin souvent confondu.','',5,'distinguer','{"principe": "Contraste consonantique fin : liquide latérale [l] contre liquide vibrante [r]", "paires": [{"mots": ["lit", "riz"]}, {"mots": ["long", "rond"]}, {"mots": ["lourd", "roux"]}, {"mots": ["loup", "roue"]}, {"mots": ["lampe", "rampe"]}, {"mots": ["large", "rage"]}], "instructions": "Votre partenaire prononce un mot. Retrouvez lequel parmi les deux proposés.", "consigne_partenaire": "Prononcez clairement l\'un des deux mots, dans un ordre aléatoire."}'),
(108,'Fruit ou légume ?','facile','Écoutez la description et classez l\'aliment : fruit ou légume ?','',4,'reconnaitre','{"categories": ["Fruit", "Légume"], "consigne_categorisation": "S\'agit-il d\'un fruit ou d\'un légume ?", "classification": [{"description": "Elle est jaune, on la pèle avant de la manger, et les singes l\'adorent.", "categorie": "Fruit"}, {"description": "Elle est orange, longue, et les lapins l\'adorent.", "categorie": "Légume"}, {"description": "Elle est rouge ou verte, croquante, et pousse sur un arbre.", "categorie": "Fruit"}, {"description": "Il est vert et long, on le coupe en rondelles dans la salade.", "categorie": "Légume"}, {"description": "Elle est jaune et acide, on la presse pour faire du jus.", "categorie": "Fruit"}, {"description": "Elle est blanche ou rouge, ronde, et fait pleurer quand on la coupe.", "categorie": "Légume"}], "instructions": "Votre partenaire lit la description d\'un aliment. Dites s\'il s\'agit d\'un fruit ou d\'un légume.", "consigne_partenaire": "Lisez chaque description à voix haute, dans un ordre aléatoire."}'),
(109,'Reconnaître un animal (indices simples)','facile','Votre partenaire décrit un animal avec des indices très simples. Devinez lequel.','',4,'reconnaitre','{"animaux": [{"animal": "Le poisson", "indices": ["Il vit dans l\'eau", "Il a des nageoires", "On le voit dans un aquarium"]}, {"animal": "L\'oiseau", "indices": ["Il a des ailes", "Il vole dans le ciel", "Il fait cui-cui"]}, {"animal": "Le serpent", "indices": ["Il n\'a pas de pattes", "Il rampe au sol", "Il siffle"]}, {"animal": "La tortue", "indices": ["Elle a une carapace", "Elle marche très lentement", "Elle vit très longtemps"]}, {"animal": "Le papillon", "indices": ["Il a des ailes colorées", "Il vole de fleur en fleur", "Il était une chenille avant"]}], "instructions": "Votre partenaire décrit un animal. Devinez lequel.", "consigne_partenaire": "Décrivez l\'animal sans le nommer : où il vit, ce qu\'il fait, son apparence."}'),
(110,'Reconnaître un bruit du quotidien (indices subtils)','difficile','Votre partenaire décrit un bruit avec des indices plus subtils qu\'en niveau moyen. Devinez de quoi il s\'agit.','',4,'reconnaitre','{"sons": [{"son": "Une craie sur un tableau", "description": "Un son aigu et désagréable qui fait grincer des dents"}, {"son": "Un frigo qui ronronne", "description": "Un bourdonnement grave et continu, presque imperceptible"}, {"son": "Une bougie qu\'on souffle", "description": "Un souffle bref suivi du silence"}, {"son": "Une enveloppe qu\'on déchire", "description": "Un bruit sec et irrégulier de papier qui se déchire"}, {"son": "Un stylo qui clique", "description": "Un clic métallique très bref"}, {"son": "Une fermeture éclair", "description": "Un glissement métallique continu"}], "instructions": "Votre partenaire décrit un son sans le nommer. Devinez de quel son il s\'agit.", "consigne_partenaire": "Décrivez le son avec des mots, sans le nommer directement."}'),
(111,'Retenir 2 mots','facile','Votre partenaire vous lit deux mots. Répétez-les immédiatement, dans le bon ordre.','',7,'memoriser','{"listes": [{"theme": "Deux objets", "elements": ["clé", "stylo"]}, {"theme": "Deux fruits", "elements": ["pomme", "banane"]}, {"theme": "Deux couleurs", "elements": ["rouge", "bleu"]}, {"theme": "Deux animaux", "elements": ["chat", "chien"]}, {"theme": "Deux boissons", "elements": ["eau", "café"]}], "instructions": "Votre partenaire vous lit deux mots. Répétez-les immédiatement, dans le bon ordre.", "consigne_partenaire": "Lisez les deux mots une seule fois, demandez à l\'auditeur de les répéter aussitôt."}'),
(112,'Retenir 3 objets du quotidien','facile','Votre partenaire vous lit trois mots. Répétez-les immédiatement, dans le bon ordre.','',7,'memoriser','{"listes": [{"theme": "Objets sur la table", "elements": ["assiette", "verre", "fourchette"]}, {"theme": "Vêtements", "elements": ["chaussette", "pull", "écharpe"]}, {"theme": "Fruits", "elements": ["fraise", "poire", "abricot"]}, {"theme": "Outils", "elements": ["marteau", "tournevis", "clou"]}, {"theme": "Animaux de compagnie", "elements": ["chat", "chien", "poisson"]}], "instructions": "Répétez immédiatement les 3 mots entendus, dans l\'ordre.", "consigne_partenaire": "Lisez la liste une seule fois à vitesse normale, puis demandez la répétition aussitôt."}'),
(113,'Petite séquence à reproduire','facile','Votre partenaire énonce une courte séquence de 2 éléments. Répétez-la dans le même ordre.','',7,'memoriser','{"sequences": [{"contexte": "Gestes simples", "elements": ["lever la main", "taper des mains"]}, {"contexte": "Deux couleurs dans l\'ordre", "elements": ["rouge", "bleu"]}, {"contexte": "Deux chiffres", "elements": ["trois", "sept"]}, {"contexte": "Deux directions", "elements": ["à gauche", "à droite"]}, {"contexte": "Deux jours", "elements": ["lundi", "mardi"]}], "instructions": "Votre partenaire énonce une courte séquence de 2 éléments. Répétez-la dans le même ordre.", "consigne_partenaire": "Lisez la séquence une seule fois, demandez la répétition aussitôt."}'),
(114,'Retenir un petit numéro','facile','Votre partenaire énonce trois chiffres. Répétez-les dans le même ordre.','',7,'memoriser','{"sequences": [{"contexte": "Trois chiffres", "elements": ["cinq", "deux", "huit"]}, {"contexte": "Trois chiffres", "elements": ["neuf", "un", "quatre"]}, {"contexte": "Trois chiffres", "elements": ["sept", "trois", "six"]}, {"contexte": "Trois chiffres", "elements": ["deux", "huit", "cinq"]}, {"contexte": "Trois chiffres", "elements": ["quatre", "neuf", "un"]}], "instructions": "Votre partenaire énonce trois chiffres. Répétez-les dans le même ordre.", "consigne_partenaire": "Énoncez les trois chiffres à vitesse normale, avec une courte pause entre chaque."}'),
(115,'Retenir 2 tâches à faire','facile','Votre partenaire vous lit deux tâches. Répétez-les immédiatement, dans l\'ordre.','',7,'memoriser','{"listes": [{"theme": "Deux courses", "elements": ["du pain", "du lait"]}, {"theme": "Deux tâches", "elements": ["arroser les plantes", "sortir la poubelle"]}, {"theme": "Deux appels", "elements": ["appeler le médecin", "appeler Sophie"]}, {"theme": "Deux achats", "elements": ["des œufs", "du beurre"]}, {"theme": "Deux rendez-vous", "elements": ["le dentiste", "le coiffeur"]}], "instructions": "Votre partenaire vous lit deux tâches. Répétez-les immédiatement, dans l\'ordre.", "consigne_partenaire": "Lisez la liste une seule fois, demandez la répétition aussitôt."}'),
(116,'Retenir 4 mots','moyen','Votre partenaire vous lit quatre mots. Répétez-les dans le bon ordre.','',7,'memoriser','{"listes": [{"theme": "Quatre objets de bureau", "elements": ["stylo", "agrafeuse", "classeur", "ciseaux"]}, {"theme": "Quatre légumes", "elements": ["carotte", "poireau", "tomate", "courgette"]}, {"theme": "Quatre pays", "elements": ["France", "Espagne", "Italie", "Portugal"]}, {"theme": "Quatre sports", "elements": ["natation", "tennis", "football", "vélo"]}, {"theme": "Quatre villes", "elements": ["Nice", "Toulouse", "Nantes", "Strasbourg"]}], "instructions": "Votre partenaire vous lit quatre mots. Répétez-les dans le bon ordre.", "consigne_partenaire": "Lisez la liste une seule fois à vitesse normale, puis demandez la répétition."}'),
(117,'Suivre une consigne à retenir puis exécuter','moyen','Mémorisez la consigne, patientez pendant que votre partenaire change de sujet, puis exécutez-la.','',7,'memoriser','{"phrases": ["Après cette phrase, touchez votre oreille.", "Dans quelques secondes, levez la main droite.", "Souvenez-vous : il faudra taper deux fois dans vos mains.", "Rappelez-vous de compter jusqu\'à cinq à voix haute.", "Retenez ceci : vous devrez montrer la fenêtre."], "instructions": "Votre partenaire énonce une consigne. Attendez qu\'il change de sujet pendant 10 secondes, puis exécutez la consigne mémorisée.", "consigne_partenaire": "Énoncez la consigne, changez de sujet pendant environ 10 secondes, puis demandez à l\'auditeur d\'exécuter ce qui a été demandé."}'),
(118,'Retenir une séquence de 4','moyen','Votre partenaire énonce une séquence de 4 éléments. Répétez-la dans le même ordre.','',7,'memoriser','{"sequences": [{"contexte": "Quatre gestes", "elements": ["lever la main", "toucher le nez", "taper des mains", "fermer les yeux"]}, {"contexte": "Quatre chiffres", "elements": ["deux", "sept", "quatre", "neuf"]}, {"contexte": "Quatre directions", "elements": ["tout droit", "à gauche", "à droite", "tout droit"]}, {"contexte": "Quatre courses", "elements": ["pain", "lait", "beurre", "œufs"]}, {"contexte": "Quatre jours", "elements": ["lundi", "mercredi", "vendredi", "dimanche"]}], "instructions": "Votre partenaire énonce une séquence de 4 éléments. Répétez-la dans le même ordre.", "consigne_partenaire": "Lisez la séquence une seule fois, demandez la répétition aussitôt."}'),
(119,'Mémoriser un court itinéraire','moyen','Votre partenaire décrit un petit itinéraire en 3 étapes. Répétez-le dans le bon ordre.','',7,'memoriser','{"sequences": [{"contexte": "Itinéraire vers la boulangerie", "elements": ["tout droit", "à gauche au feu", "deuxième rue à droite"]}, {"contexte": "Itinéraire vers la pharmacie", "elements": ["à droite en sortant", "tout droit jusqu\'à la place", "à gauche après l\'église"]}, {"contexte": "Itinéraire vers la gare", "elements": ["à gauche", "tout droit", "à droite au rond-point"]}, {"contexte": "Itinéraire vers le parc", "elements": ["tout droit", "première à droite", "continuer jusqu\'au bout"]}], "instructions": "Votre partenaire décrit un itinéraire en plusieurs étapes. Répétez-le dans le bon ordre.", "consigne_partenaire": "Décrivez l\'itinéraire une seule fois, à vitesse normale."}'),
(120,'Thème : Les animaux domestiques','facile','Répétez des phrases courtes et simples sur le thème des animaux domestiques.','',8,'themes','{"themes": [{"theme": "Les animaux domestiques", "phrases": ["J\'ai un chat noir.", "Le chien aboie fort.", "Le poisson rouge nage dans son bocal.", "Le hamster dort dans sa cage.", "Le lapin mange une carotte."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase lentement. Attendez que l\'auditeur répète avant de continuer."}'),
(121,'Thème : L\'école','facile','Répétez des phrases courtes et simples sur le thème de l\'école.','',8,'themes','{"themes": [{"theme": "L\'école", "phrases": ["Je prends mon cartable.", "La maîtresse écrit au tableau.", "Les enfants jouent dans la cour.", "J\'apprends à lire et à écrire.", "La cloche sonne à midi."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase lentement. Attendez que l\'auditeur répète avant de continuer."}'),
(122,'Thème : Le sport','facile','Répétez des phrases courtes et simples sur le thème du sport.','',8,'themes','{"themes": [{"theme": "Le sport", "phrases": ["Je fais du vélo le dimanche.", "Il joue au football avec ses amis.", "Elle nage à la piscine.", "Nous marchons dans le parc.", "Le coureur porte un dossard."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase lentement. Attendez que l\'auditeur répète avant de continuer."}'),
(123,'Thème : Les vêtements','facile','Répétez des phrases courtes et simples sur le thème des vêtements.','',8,'themes','{"themes": [{"theme": "Les vêtements", "phrases": ["Je mets mon pull rouge.", "Elle porte une jupe bleue.", "Il enfile ses chaussettes.", "J\'attache mes chaussures.", "Elle range son manteau."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase lentement. Attendez que l\'auditeur répète avant de continuer."}'),
(124,'Thème : La cuisine','facile','Répétez des phrases courtes et simples sur le thème de la cuisine.','',8,'themes','{"themes": [{"theme": "La cuisine", "phrases": ["Je fais bouillir de l\'eau.", "Elle épluche les pommes de terre.", "Il met la table pour le dîner.", "Je lave les assiettes.", "Le gâteau cuit dans le four."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase lentement. Attendez que l\'auditeur répète avant de continuer."}'),
(125,'Thème : Les couleurs','facile','Répétez des phrases courtes et simples sur le thème des couleurs.','',8,'themes','{"themes": [{"theme": "Les couleurs", "phrases": ["Le ciel est bleu aujourd\'hui.", "Sa robe est verte.", "J\'aime le jaune et l\'orange.", "La voiture est rouge vif.", "Le chat est tout noir."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase lentement. Attendez que l\'auditeur répète avant de continuer."}'),
(126,'Thème : Le jardin','moyen','Répétez des phrases un peu plus longues sur le thème du jardin.','',8,'themes','{"themes": [{"theme": "Le jardin", "phrases": ["Il taille les rosiers tous les printemps.", "Les tomates poussent bien cette année.", "Elle arrose les fleurs chaque soir avant le coucher du soleil.", "Le chat se promène tranquillement entre les massifs.", "Nous avons planté un nouveau cerisier au fond du jardin."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase à vitesse normale. Attendez que l\'auditeur répète avant de continuer."}'),
(127,'Thème : Les fêtes','moyen','Répétez des phrases un peu plus longues sur le thème des fêtes.','',8,'themes','{"themes": [{"theme": "Les fêtes", "phrases": ["Nous décorons le sapin de Noël ensemble chaque année.", "Toute la famille se réunit pour l\'anniversaire de grand-mère.", "Les enfants adorent chercher les œufs de Pâques dans le jardin.", "On allume un feu d\'artifice pour le nouvel an.", "Elle prépare un gâteau pour fêter la nouvelle année."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase à vitesse normale. Attendez que l\'auditeur répète avant de continuer."}'),
(128,'Thème : La ville','moyen','Répétez des phrases un peu plus longues sur le thème de la ville.','',8,'themes','{"themes": [{"theme": "La ville", "phrases": ["Le marché du centre-ville a lieu tous les samedis matin.", "Il y a beaucoup de monde dans les rues piétonnes cet après-midi.", "Le bus s\'arrête juste devant la mairie.", "Les commerces ferment plus tôt le dimanche.", "On peut se garer facilement près de la bibliothèque municipale."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase à vitesse normale. Attendez que l\'auditeur répète avant de continuer."}'),
(129,'Thème : Le bureau','moyen','Répétez des phrases un peu plus longues sur le thème du bureau.','',8,'themes','{"themes": [{"theme": "Le bureau", "phrases": ["La réunion commence à neuf heures précises ce matin.", "Elle envoie un mail à son collègue avant midi.", "L\'imprimante est encore en panne au deuxième étage.", "Il prend une pause-café avec ses collègues vers dix heures.", "Le rapport doit être terminé avant la fin de la semaine."]}], "instructions": "Votre partenaire annonce le thème, puis lit chaque phrase. Répétez-la.", "consigne_partenaire": "Annoncez le thème. Lisez chaque phrase à vitesse normale. Attendez que l\'auditeur répète avant de continuer."}');
