-- ================================================================
-- MIGRATION INCRÉMENTALE — 29 septembre 2026
-- ================================================================
-- Contrairement à setup_complet.sql (qui DROP puis recrée toutes les
-- tables), ce script est additif : à exécuter UNE SEULE FOIS sur la
-- base de production existante, sans rien supprimer.
--
-- Avant de lancer :
--   1. Faire une sauvegarde (./BDD/backup.sh ou mysqldump manuel).
--   2. Vérifier qu'aucun exercice d'id 76 à 95 n'existe déjà en base
--      (SELECT id FROM Exercices WHERE id BETWEEN 76 AND 95;) —
--      sinon les INSERT plus bas échoueront sur la clé primaire.
--   3. Ne PAS relancer ce fichier une seconde fois tel quel (les
--      INSERT ne sont pas idempotents).
--
-- Contenu :
--   A. Colonnes FSRS sur Revisions (remplace l'algo SM-2 par FSRS,
--      cf. backend/src/controllers/queteController.ts)
--   B. 17 nouveaux exercices (détection/discrimination non-verbales,
--      classification, intrus, consignes progressives, dialogues)
--   C. 3 exercices pour activer le composant "décision orthographique"
--      (codé mais jusqu'ici sans aucun contenu en base)
--   D. Élargissement de 12 banques de mots/items trop courtes
-- ================================================================

-- ── A. Colonnes FSRS sur Revisions ─────────────────────────────
ALTER TABLE Revisions
  ADD COLUMN stabilite         DOUBLE DEFAULT NULL AFTER nb_revisions,
  ADD COLUMN difficulte        DOUBLE DEFAULT NULL AFTER stabilite,
  ADD COLUMN etat              TINYINT NOT NULL DEFAULT 0 AFTER difficulte,
  ADD COLUMN nb_echecs         INT NOT NULL DEFAULT 0 AFTER etat,
  ADD COLUMN derniere_revision DATETIME DEFAULT NULL AFTER nb_echecs;

-- ── B. + C. + D. Nouveaux exercices et banques élargies ────────

-- ── Nouveaux exercices : détection/discrimination non-verbales, classification,
--    intrus, consignes progressives, dialogues (cf. référentiel détection/discrimination/
--    identification/compréhension) ───────────────────────────────

INSERT INTO `Exercices` (`id`, `titre`, `niveau`, `description`, `audio_url`, `categorie_id`, `type_exercice`, `contenu`) VALUES
(76,'Jouets sonores','facile','Cliquez chaque fois que vous entendez un son de jouet ou d\'objet familier (hochet, clochette, grelot...).','',3,'detecter',NULL),
(77,'Cris d\'animaux et bruits du quotidien','moyen','Cliquez à chaque son : cri d\'animal, klaxon, sonnette, aboiement... Le rythme est plus dense qu\'en niveau facile.','',3,'detecter',NULL),
(78,'Détection en environnement bruyant','difficile','Repérez chaque son alors qu\'un bruit de fond est présent — comme dans une pièce animée ou une rue passante.','',3,'detecter',NULL),
(79,'Sons purs : pareil ou différent ?','facile','Deux sons sont joués l\'un après l\'autre. Sont-ils identiques ou différents ? Les hauteurs sont très éloignées.','',5,'distinguer',NULL),
(80,'Comparaison fine de hauteur sonore','moyen','Comparez deux sons dont la hauteur se rapproche — un écart d\'un ton environ.','',5,'distinguer',NULL),
(81,'Discrimination fine en bruit de fond','difficile','Comparez deux sons très proches (un demi-ton d\'écart) avec un bruit de fond présent en continu.','',5,'distinguer',NULL),
(82,'Nature ou machine ?','facile','Écoutez la description du bruit et classez-le : vient-il de la nature ou d\'une machine ?','',4,'reconnaitre','{"categories": ["Nature", "Machine"], "consigne_categorisation": "Ce bruit vient-il de la nature ou d\'une machine ?", "classification": [{"description": "Le vent qui souffle fort dans les arbres.", "categorie": "Nature"}, {"description": "Un moteur de voiture qui démarre.", "categorie": "Machine"}, {"description": "Des vagues qui s\'écrasent sur la plage.", "categorie": "Nature"}, {"description": "Une perceuse électrique.", "categorie": "Machine"}, {"description": "La pluie qui tombe sur un toit.", "categorie": "Nature"}, {"description": "Un aspirateur en marche.", "categorie": "Machine"}, {"description": "Le tonnerre qui gronde au loin.", "categorie": "Nature"}, {"description": "Une imprimante qui fonctionne.", "categorie": "Machine"}], "instructions": "Votre partenaire lit la description d\'un bruit. Dites s\'il provient de la nature ou d\'une machine.", "consigne_partenaire": "Lisez chaque description à voix haute, dans un ordre aléatoire."}'),
(83,'Familles d\'instruments de musique','moyen','Classez chaque instrument décrit dans sa famille : percussions, vent ou cordes.','',4,'reconnaitre','{"categories": ["Percussions", "Vent", "Cordes"], "consigne_categorisation": "À quelle famille appartient cet instrument ?", "classification": [{"description": "Le tambour, que l\'on frappe avec des baguettes.", "categorie": "Percussions"}, {"description": "La flûte traversière, dans laquelle on souffle.", "categorie": "Vent"}, {"description": "Le violon, dont on frotte les cordes avec un archet.", "categorie": "Cordes"}, {"description": "Les cymbales, que l\'on entrechoque.", "categorie": "Percussions"}, {"description": "La trompette, dans laquelle on souffle avec les lèvres.", "categorie": "Vent"}, {"description": "La guitare, dont on pince les cordes.", "categorie": "Cordes"}, {"description": "Le xylophone, que l\'on frappe avec des maillets.", "categorie": "Percussions"}, {"description": "Le saxophone, dans lequel on souffle.", "categorie": "Vent"}, {"description": "La harpe, dont on pince les cordes.", "categorie": "Cordes"}], "instructions": "Votre partenaire décrit un instrument. Dites à quelle famille il appartient.", "consigne_partenaire": "Lisez chaque description à voix haute, dans un ordre aléatoire."}'),
(84,'Bruits domestiques par pièce','difficile','Classez chaque bruit du quotidien selon la pièce de la maison où on l\'entend le plus souvent.','',4,'reconnaitre','{"categories": ["Cuisine", "Salle de bain", "Jardin", "Rue"], "consigne_categorisation": "Dans quelle pièce ou quel lieu entend-on le plus souvent ce bruit ?", "classification": [{"description": "Le sifflement d\'une bouilloire.", "categorie": "Cuisine"}, {"description": "L\'eau qui coule dans la douche.", "categorie": "Salle de bain"}, {"description": "Une tondeuse à gazon en marche.", "categorie": "Jardin"}, {"description": "Le klaxon d\'une voiture.", "categorie": "Rue"}, {"description": "Le mixeur qui broie des légumes.", "categorie": "Cuisine"}, {"description": "Le sèche-cheveux.", "categorie": "Salle de bain"}, {"description": "Le chant des oiseaux dans les arbres.", "categorie": "Jardin"}, {"description": "Une sirène de pompiers au loin.", "categorie": "Rue"}, {"description": "Le grille-pain qui éjecte les tartines.", "categorie": "Cuisine"}], "instructions": "Votre partenaire décrit un bruit. Dites dans quel lieu on l\'entend le plus souvent.", "consigne_partenaire": "Lisez chaque description à voix haute, dans un ordre aléatoire."}'),
(85,'Trouvez l\'intrus (mots)','facile','Une liste de mots est énoncée. Un seul n\'appartient pas au même thème que les autres : trouvez-le.','',4,'reconnaitre','{"listes_intrus": [{"items": ["chat", "chien", "cheval", "voiture"], "intrus": "voiture"}, {"items": ["pomme", "banane", "fraise", "chaise"], "intrus": "chaise"}, {"items": ["rouge", "bleu", "vert", "triste"], "intrus": "triste"}, {"items": ["table", "chaise", "armoire", "soleil"], "intrus": "soleil"}, {"items": ["lundi", "mardi", "jeudi", "avril"], "intrus": "avril"}], "instructions": "Votre partenaire énonce une liste de mots. Trouvez celui qui n\'appartient pas au même thème.", "consigne_partenaire": "Prononcez chaque liste de mots clairement, dans l\'ordre indiqué."}'),
(86,'Trouvez l\'intrus (syllabes proches)','moyen','Une liste de syllabes très proches est énoncée. Une seule diffère des autres par un trait phonétique : trouvez-la.','',4,'reconnaitre','{"listes_intrus": [{"items": ["pa", "pa", "ba", "pa"], "intrus": "ba"}, {"items": ["ta", "ta", "ta", "da"], "intrus": "da"}, {"items": ["fou", "fou", "vou", "fou"], "intrus": "vou"}, {"items": ["chi", "chi", "ji", "chi"], "intrus": "ji"}, {"items": ["ka", "ga", "ka", "ka"], "intrus": "ga"}], "instructions": "Votre partenaire prononce une série de syllabes très proches. Trouvez celle qui diffère des autres.", "consigne_partenaire": "Prononcez chaque série lentement et clairement, dans l\'ordre indiqué."}'),
(87,'Trouvez l\'intrus (phrases proches)','difficile','Une liste de phrases phonétiquement proches est énoncée. Une seule a un sens différent des autres : trouvez-la.','',4,'reconnaitre','{"listes_intrus": [{"items": ["Il fait beau", "Il fait chaud", "Il fait faux", "Il fait doux"], "intrus": "Il fait faux"}, {"items": ["Elle a ri", "Elle a lu", "Elle a su", "Elle a vu"], "intrus": "Elle a ri"}, {"items": ["Je pars demain", "Je cours demain", "Je dors demain", "Je sors demain"], "intrus": "Je cours demain"}], "instructions": "Votre partenaire prononce une série de phrases très proches. Trouvez celle dont le sens diffère des autres.", "consigne_partenaire": "Prononcez chaque série lentement et clairement, dans l\'ordre indiqué."}'),
(88,'Suivez la consigne (simple)','facile','Écoutez une consigne à une seule action et exécutez-la avec votre partenaire.','',6,'comprendre','{"phrases": ["Levez la main droite.", "Touchez votre nez.", "Fermez les yeux.", "Montrez la porte.", "Tapez dans vos mains."], "instructions": "Votre partenaire énonce une consigne simple. Exécutez-la, puis indiquez si vous avez réussi.", "consigne_partenaire": "Énoncez chaque consigne clairement, une seule action à la fois."}'),
(89,'Suivez la consigne (à deux étapes)','moyen','Écoutez une consigne à deux actions successives et exécutez-les dans l\'ordre.','',6,'comprendre','{"phrases": ["Levez la main puis touchez votre oreille.", "Fermez les yeux puis comptez jusqu\'à trois.", "Montrez la fenêtre puis asseyez-vous.", "Touchez votre tête puis tapez dans vos mains.", "Levez-vous puis tournez sur vous-même."], "instructions": "Votre partenaire énonce une consigne à deux étapes. Exécutez les deux actions dans l\'ordre, puis indiquez si vous avez réussi.", "consigne_partenaire": "Énoncez chaque consigne d\'une traite, sans répéter."}'),
(90,'Suivez la consigne (complexe)','difficile','Écoutez une consigne à plusieurs étapes, avec une condition, et exécutez-la.','',6,'comprendre','{"phrases": ["Si la porte est fermée, levez la main ; sinon, tapez dans vos mains.", "Touchez d\'abord votre nez, puis votre oreille gauche, puis asseyez-vous.", "Comptez jusqu\'à trois, puis fermez les yeux jusqu\'à ce qu\'on vous touche l\'épaule.", "Montrez la fenêtre si elle est ouverte, sinon montrez la porte."], "instructions": "Votre partenaire énonce une consigne complexe, avec plusieurs étapes ou une condition. Exécutez-la, puis indiquez si vous avez réussi.", "consigne_partenaire": "Énoncez la consigne complète d\'une traite, sans la répéter ni la simplifier."}'),
(91,'Dialogue du quotidien','moyen','Votre partenaire vous parle comme dans une conversation réelle. Répondez du mieux possible, avec lecture labiale si besoin.','',6,'comprendre','{"phrases": ["Qu\'est-ce que tu as prévu de faire ce week-end ?", "Est-ce que tu as bien dormi cette nuit ?", "Qu\'est-ce qu\'on mange ce soir, tu as une idée ?", "Tu as des nouvelles de la famille ?", "Comment s\'est passée ta journée ?"], "instructions": "Votre partenaire vous pose une question naturelle comme dans une vraie conversation. Répondez-y, puis indiquez si l\'échange s\'est bien passé.", "consigne_partenaire": "Posez chaque question naturellement, comme dans une conversation, en gardant votre visage visible."}'),
(92,'Conversation au téléphone','difficile','Votre partenaire vous parle depuis une autre pièce ou au téléphone : pas de lecture labiale possible, seul le son compte.','',6,'comprendre','{"phrases": ["Allô, tu m\'entends bien ?", "Je t\'appelle pour te dire que je serai en retard.", "Tu peux me rappeler ce soir vers dix-neuf heures ?", "Est-ce que tu as reçu le message que je t\'ai envoyé ?", "On se retrouve à quelle heure demain ?"], "instructions": "Votre partenaire vous parle sans que vous puissiez le voir (au téléphone ou depuis une autre pièce). Répondez comme dans un vrai appel, puis indiquez si vous avez bien compris.", "consigne_partenaire": "Lisez chaque phrase depuis une autre pièce, ou appelez réellement au téléphone, sans vous laisser voir."}');

-- ── Activation du composant "décision orthographique" (jusqu'ici sans contenu seedé) ──

INSERT INTO `Exercices` (`id`, `titre`, `niveau`, `description`, `audio_url`, `categorie_id`, `type_exercice`, `contenu`) VALUES
(93,'Quel mot avez-vous entendu ? (mots très différents)','facile','Écoutez le mot prononcé et retrouvez-le parmi des mots très différents.','',4,'decision_orthographique','{"mots": [{"mot": "chat", "choix": ["chat", "vélo", "arbre", "table"]}, {"mot": "maison", "choix": ["voiture", "maison", "soleil", "fleur"]}, {"mot": "livre", "choix": ["porte", "musique", "livre", "nuage"]}, {"mot": "jardin", "choix": ["jardin", "montagne", "cuisine", "bureau"]}, {"mot": "pomme", "choix": ["orange", "pomme", "banane", "raisin"]}, {"mot": "école", "choix": ["hôpital", "gare", "école", "magasin"]}], "instructions": "Votre partenaire prononce un mot. Retrouvez-le parmi les mots proposés.", "consigne_partenaire": "Prononcez clairement un seul mot parmi les quatre proposés, dans un ordre aléatoire."}'),
(94,'Quel mot avez-vous entendu ? (mots proches)','moyen','Écoutez le mot prononcé et retrouvez-le parmi des mots qui se ressemblent un peu.','',4,'decision_orthographique','{"mots": [{"mot": "poisson", "choix": ["poisson", "boisson", "poison", "prison"]}, {"mot": "bateau", "choix": ["bateau", "chapeau", "gâteau", "rideau"]}, {"mot": "manteau", "choix": ["manteau", "marteau", "morceau", "monceau"]}, {"mot": "caisse", "choix": ["caisse", "fraise", "chaise", "braise"]}, {"mot": "coussin", "choix": ["coussin", "cousin", "poussin", "moussu"]}, {"mot": "raisin", "choix": ["raisin", "requin", "rasoir", "raison"]}], "instructions": "Votre partenaire prononce un mot. Retrouvez-le parmi des mots qui se ressemblent.", "consigne_partenaire": "Prononcez clairement un seul mot parmi les quatre proposés, dans un ordre aléatoire."}'),
(95,'Quel mot avez-vous entendu ? (paires minimales)','difficile','Écoutez le mot prononcé et retrouvez-le parmi des mots qui ne diffèrent que d\'un seul son.','',4,'decision_orthographique','{"mots": [{"mot": "pain", "choix": ["pain", "bain", "vin", "lin"]}, {"mot": "tante", "choix": ["tante", "dante", "sente", "vente"]}, {"mot": "chou", "choix": ["chou", "joue", "coup", "roue"]}, {"mot": "pont", "choix": ["pont", "bond", "ton", "don"]}, {"mot": "gare", "choix": ["gare", "car", "mare", "bar"]}, {"mot": "vase", "choix": ["vase", "base", "case", "phase"]}], "instructions": "Votre partenaire prononce un mot. Retrouvez-le parmi des mots très proches phonétiquement.", "consigne_partenaire": "Prononcez clairement un seul mot parmi les quatre proposés, dans un ordre aléatoire."}');

-- ── Élargissement des banques de mots/items trop courtes (répétition trop rapide en SRS) ──

UPDATE `Exercices` SET `contenu` = '{"animaux": [{"animal": "Le chien", "indices": ["C\'est un animal domestique", "Il aboie", "Il est souvent appelé meilleur ami de l\'homme"]}, {"animal": "Le chat", "indices": ["Il ronronne", "Il aime dormir au soleil", "Il est très indépendant"]}, {"animal": "Le coq", "indices": ["Il chante le matin", "Il vit à la ferme", "Il a un plumage coloré"]}, {"animal": "La grenouille", "indices": ["Elle coasse", "Elle vit près de l\'eau", "Elle saute très haut"]}, {"animal": "L\'éléphant", "indices": ["C\'est le plus grand animal terrestre", "Il a une trompe", "Il vit en Afrique ou en Asie"]}, {"animal": "Le hibou", "indices": ["Il sort la nuit", "Il fait \'hou hou\'", "Il tourne la tête à 270 degrés"]}, {"animal": "La vache", "indices": ["Elle vit à la ferme", "Elle donne du lait", "Elle fait \'meuh\'"]}, {"animal": "Le canard", "indices": ["Il nage sur l\'eau", "Il fait \'coin coin\'", "Il a des pattes palmées"]}, {"animal": "Le lion", "indices": ["On l\'appelle le roi des animaux", "Il vit en Afrique", "Il a une grande crinière"]}, {"animal": "La souris", "indices": ["Elle est toute petite", "Elle aime le fromage", "Les chats la chassent"]}, {"animal": "Le dauphin", "indices": ["Il vit dans la mer", "Il est très intelligent", "Il communique par sifflements"]}, {"animal": "L\'abeille", "indices": ["Elle fabrique du miel", "Elle vit en colonie", "Elle peut piquer"]}], "instructions": "Votre partenaire décrit un animal. Devinez lequel.", "consigne_partenaire": "Décrivez l\'animal sans le nommer : où il vit, ce qu\'il mange, ses caractéristiques."}' WHERE `id` = 6;
UPDATE `Exercices` SET `contenu` = '{"instruments": [{"indices": ["On appuie sur des touches noires et blanches", "Il peut être très grand", "Beethoven en jouait"], "instrument": "Le piano"}, {"indices": ["On pince des cordes", "On peut en jouer assis", "Très utilisée en rock"], "instrument": "La guitare"}, {"indices": ["On le tient sous le menton", "On utilise un archet", "C\'est un instrument à cordes frottées"], "instrument": "Le violon"}, {"indices": ["On souffle dedans", "C\'est un tube long et fin", "Elle produit des sons aigus"], "instrument": "La flûte"}, {"indices": ["On le frappe avec des baguettes", "Il donne le rythme", "Il est composé de plusieurs tambours"], "instrument": "La batterie"}, {"instrument": "Le saxophone", "indices": ["On souffle dedans avec une anche", "Très utilisé dans le jazz", "Il est en métal et brillant"]}, {"instrument": "Le tambourin", "indices": ["On le secoue et on le frappe", "Il a des petites cymbales autour", "Utilisé dans la musique traditionnelle"]}, {"instrument": "La harpe", "indices": ["Elle a de nombreuses cordes verticales", "On la pince avec les doigts", "Elle est très grande"]}, {"instrument": "L\'accordéon", "indices": ["On le tient avec les deux mains", "Il faut le compresser pour jouer", "Très présent dans la musique musette"]}, {"instrument": "Le tambour", "indices": ["On le frappe avec des baguettes ou les mains", "Il est rond et creux", "Utilisé dans de nombreuses cultures"]}], "instructions": "Votre partenaire décrit un instrument de musique. Nommez-le.", "consigne_partenaire": "Décrivez l\'instrument sans le nommer : apparence, comment on en joue, quel son il produit."}' WHERE `id` = 7;
UPDATE `Exercices` SET `contenu` = '{"rythmes": [{"notation": "court-court-long", "description": "2 frappes rapides puis 1 longue"}, {"notation": "long-court-court-court", "description": "1 longue puis 3 rapides"}, {"notation": "court-long-court", "description": "1 courte, 1 longue, 1 courte"}, {"notation": "long-long-court", "description": "2 longues puis 1 courte"}, {"notation": "court-court-court-long", "description": "3 rapides puis 1 longue"}, {"notation": "court-court-court", "description": "3 frappes rapides et régulières"}, {"notation": "long-long-long", "description": "3 frappes longues et espacées"}, {"notation": "court-long-long-court", "description": "1 courte, 2 longues, 1 courte"}, {"notation": "long-court-long", "description": "1 longue, 1 courte, 1 longue"}, {"notation": "court-court-long-court", "description": "2 rapides, 1 longue, 1 courte"}], "instructions": "Écoutez le rythme frappé par votre partenaire et reproduisez-le.", "consigne_partenaire": "Frappez chaque rythme sur la table. L\'auditeur doit le reproduire."}' WHERE `id` = 10;
UPDATE `Exercices` SET `contenu` = '{"paires": [{"mot1": "pain", "mot2": "bain", "resultat": "différent"}, {"mot1": "sou", "mot2": "sou", "resultat": "pareil"}, {"mot1": "mer", "mot2": "mer", "resultat": "pareil"}, {"mot1": "vert", "mot2": "fer", "resultat": "différent"}, {"mot1": "vin", "mot2": "lin", "resultat": "différent"}, {"mot1": "rue", "mot2": "rue", "resultat": "pareil"}, {"mot1": "feu", "mot2": "jeu", "resultat": "différent"}, {"mot1": "lac", "mot2": "lac", "resultat": "pareil"}, {"mot1": "doux", "mot2": "tout", "resultat": "différent"}, {"mot1": "riz", "mot2": "riz", "resultat": "pareil"}, {"mot1": "banc", "mot2": "blanc", "resultat": "différent"}, {"mot1": "sel", "mot2": "sel", "resultat": "pareil"}], "instructions": "Votre partenaire prononce deux mots. Dites s\'ils sont pareils ou différents.", "consigne_partenaire": "Prononcez les deux mots l\'un après l\'autre. Certaines paires sont identiques."}' WHERE `id` = 11;
UPDATE `Exercices` SET `contenu` = '{"paires": [{"mot1": "pont", "mot2": "bond", "resultat": "différent"}, {"mot1": "tôt", "mot2": "tôt", "resultat": "pareil"}, {"mot1": "cou", "mot2": "genou", "resultat": "différent"}, {"mot1": "chat", "mot2": "gat", "resultat": "différent"}, {"mot1": "fin", "mot2": "fin", "resultat": "pareil"}, {"mot1": "belle", "mot2": "pelle", "resultat": "différent"}, {"mot1": "quai", "mot2": "gai", "resultat": "différent"}, {"mot1": "roue", "mot2": "roue", "resultat": "pareil"}, {"mot1": "dos", "mot2": "faux", "resultat": "différent"}, {"mot1": "nid", "mot2": "nid", "resultat": "pareil"}, {"mot1": "bulle", "mot2": "pull", "resultat": "différent"}, {"mot1": "lame", "mot2": "lame", "resultat": "pareil"}], "instructions": "Votre partenaire prononce deux mots. Dites s\'ils sont pareils ou différents.", "consigne_partenaire": "Prononcez les deux mots l\'un après l\'autre. Niveau plus difficile."}' WHERE `id` = 12;
UPDATE `Exercices` SET `contenu` = '{"sons": [{"son": "La pluie", "description": "C\'est un bruit continu de gouttes qui tombent sur les vitres"}, {"son": "La sonnerie du téléphone", "description": "C\'est un son répétitif qui vous appelle à répondre"}, {"son": "Le micro-ondes", "description": "C\'est un bip court qui annonce que votre plat est chaud"}, {"son": "Un chien qui aboie", "description": "C\'est le cri d\'un animal domestique qui surveille la maison"}, {"son": "La cafetière", "description": "C\'est un gargouillis régulier qui prépare votre boisson du matin"}, {"son": "Une clé dans la serrure", "description": "C\'est un bruit métallique suivi d\'un clic quand on entre chez soi"}, {"son": "Un réveil qui sonne", "description": "C\'est un bip strident et répété qui vous sort du sommeil"}, {"son": "Une porte qui grince", "description": "C\'est un son aigu et prolongé quand on l\'ouvre lentement"}, {"son": "Le lave-linge en essorage", "description": "C\'est un vrombissement rapide et vibrant en fin de cycle"}, {"son": "Un verre qui se brise", "description": "C\'est un bruit sec et cristallin suivi de petits éclats"}, {"son": "Une scie électrique", "description": "C\'est un grondement aigu et continu qui découpe le bois"}, {"son": "Des pas dans l\'escalier", "description": "C\'est une série de bruits sourds et réguliers qui se rapprochent"}], "instructions": "Votre partenaire décrit un son sans le nommer. Devinez de quel son il s\'agit.", "consigne_partenaire": "Décrivez le son avec des mots, sans le nommer directement."}' WHERE `id` = 15;
UPDATE `Exercices` SET `contenu` = '{"paires": [{"mot_aigu": "oiseau", "mot_grave": "voiture"}, {"mot_aigu": "flûte", "mot_grave": "montagne"}, {"mot_aigu": "cloche", "mot_grave": "tambour"}, {"mot_aigu": "cigale", "mot_grave": "forêt"}, {"mot_aigu": "sifflet", "mot_grave": "tonnerre"}, {"mot_aigu": "grillon", "mot_grave": "camion"}, {"mot_aigu": "pipeau", "mot_grave": "orage"}, {"mot_aigu": "souris", "mot_grave": "baleine"}, {"mot_aigu": "triangle", "mot_grave": "gong"}, {"mot_aigu": "moustique", "mot_grave": "ours"}], "instructions": "Votre partenaire prononce deux mots, l\'un grave l\'un aigu. Identifiez lequel est grave.", "consigne_partenaire": "Prononcez les deux mots dans un ordre aléatoire, l\'un grave, l\'autre aigu."}' WHERE `id` = 18;
UPDATE `Exercices` SET `contenu` = '{"groupes": [["mer", "mère", "maire", "mais"], ["son", "sans", "sang", "cent"], ["vert", "ver", "verre", "vers"], ["pain", "pin", "bain", "bien"], ["saint", "sain", "sein", "cinq"], ["cou", "coût", "coup", "queue"], ["sot", "seau", "sceau", "saut"], ["si", "scie", "s\'y", "ci"], ["quand", "quant", "qu\'en", "camp"], ["dans", "dent", "don", "dont"], ["au", "eau", "haut", "os"], ["temps", "tant", "taon", "tend"]], "instructions": "Votre partenaire choisit et prononce un mot parmi quatre mots très proches. Identifiez lequel.", "consigne_partenaire": "Pour chaque groupe, choisissez un mot au hasard et prononcez-le naturellement."}' WHERE `id` = 21;
UPDATE `Exercices` SET `contenu` = '{"themes": [{"theme": "La journée", "questions": ["À quelle heure vous levez-vous en général ?", "Qu\'est-ce que vous mangez au petit-déjeuner ?", "Comment venez-vous ici ce matin ?", "Avez-vous bien dormi cette nuit ?", "Qu\'avez-vous fait hier soir ?"]}, {"theme": "Les loisirs", "questions": ["Qu\'aimez-vous faire le week-end ?", "Regardez-vous souvent la télévision ?", "Avez-vous un sport préféré ?", "Lisez-vous beaucoup ?", "Aimez-vous la musique ?"]}, {"theme": "La météo et les saisons", "questions": ["Quel temps fait-il aujourd\'hui ?", "Quelle saison préférez-vous ?", "Avez-vous déjà vu de la neige ?", "Est-ce qu\'il pleut souvent chez vous ?", "Aimez-vous les jours de grand soleil ?"]}, {"theme": "La famille et les amis", "questions": ["Voyez-vous souvent votre famille ?", "Avez-vous des frères et sœurs ?", "Qui est votre meilleur ami ?", "Vous parlez souvent au téléphone avec vos proches ?", "Avez-vous des petits-enfants ?"]}], "instructions": "Votre partenaire vous pose des questions. Répondez le plus naturellement possible.", "consigne_partenaire": "Posez chaque question clairement. Si l\'auditeur ne comprend pas, reformulez."}' WHERE `id` = 25;
UPDATE `Exercices` SET `contenu` = '{"sequences": [{"contexte": "Ingrédients d\'une recette", "elements": ["farine", "oeufs", "lait", "sucre", "beurre"]}, {"contexte": "Étapes du matin", "elements": ["réveil", "douche", "petit-déjeuner", "habillage", "départ"]}, {"contexte": "Directions", "elements": ["tout droit", "à gauche", "à droite", "tout droit", "à gauche"]}, {"contexte": "Jours de rendez-vous", "elements": ["lundi matin", "mercredi après-midi", "vendredi matin"]}, {"contexte": "Liste de courses", "elements": ["tomates", "fromage", "jambon", "yaourt", "jus d\'orange"]}, {"contexte": "Étapes pour préparer un café", "elements": ["eau", "filtre", "café moulu", "sucre"]}, {"contexte": "Villes de France", "elements": ["Paris", "Lyon", "Marseille", "Bordeaux", "Lille"]}, {"contexte": "Objets à emporter en vacances", "elements": ["maillot de bain", "lunettes de soleil", "crème solaire", "passeport"]}, {"contexte": "Étapes pour se laver les mains", "elements": ["mouiller", "savonner", "frotter", "rincer", "sécher"]}, {"contexte": "Numéros à retenir", "elements": ["deux", "sept", "quatre", "neuf", "un"]}], "instructions": "Votre partenaire lit une liste de 4 à 5 éléments. Répétez-les dans le même ordre.", "consigne_partenaire": "Lisez la liste une seule fois à vitesse normale. Attendez 10 secondes avant de demander la réponse."}' WHERE `id` = 27;
UPDATE `Exercices` SET `contenu` = '{"histoires": [{"texte": "Marie se lève tôt le samedi matin. Elle prend son panier en osier et marche jusqu\'au marché du quartier. Elle achète des légumes frais : des carottes, des poireaux et des champignons. Elle s\'arrête aussi chez le fromager pour prendre un camembert. En rentrant, elle croise son voisin Paul qui promène son chien.", "titre": "Le marché du samedi", "questions": [{"reponse": "Le samedi", "question": "Quel jour Marie va-t-elle au marché ?"}, {"reponse": "Un panier en osier", "question": "Qu\'est-ce qu\'elle emporte pour faire ses courses ?"}, {"reponse": "Carottes, poireaux ou champignons", "question": "Citez deux légumes qu\'elle achète."}, {"reponse": "Un camembert", "question": "Qu\'achète-t-elle chez le fromager ?"}, {"reponse": "Son voisin Paul", "question": "Qui croise-t-elle en rentrant ?"}]}, {"texte": "Thomas a rendez-vous chez le médecin à quatorze heures trente. Il attend vingt minutes dans la salle d\'attente. Le médecin l\'examine et lui dit qu\'il a une légère grippe. Il lui prescrit du repos, beaucoup de liquides et lui donne une ordonnance. Thomas doit revenir dans une semaine si les symptômes persistent.", "titre": "Le rendez-vous médical", "questions": [{"reponse": "Quatorze heures trente", "question": "À quelle heure est le rendez-vous de Thomas ?"}, {"reponse": "Vingt minutes", "question": "Combien de temps attend-il ?"}, {"reponse": "Une légère grippe", "question": "Quel est le diagnostic ?"}, {"reponse": "Du repos et beaucoup de liquides", "question": "Que lui conseille le médecin ?"}, {"reponse": "Dans une semaine", "question": "Quand doit-il revenir ?"}]}, {"titre": "La randonnée en montagne", "texte": "Le dimanche matin, Julien part en randonnée avec deux amis. Ils montent pendant deux heures jusqu\'à un petit lac de montagne. Ils pique-niquent sur un rocher en admirant le paysage. Sur le chemin du retour, il commence à pleuvoir et ils doivent accélérer le pas. Ils rentrent trempés mais heureux de leur journée.", "questions": [{"question": "Quel jour Julien part-il en randonnée ?", "reponse": "Le dimanche"}, {"question": "Avec combien d\'amis part-il ?", "reponse": "Deux amis"}, {"question": "Où pique-niquent-ils ?", "reponse": "Sur un rocher, près d\'un lac de montagne"}, {"question": "Que se passe-t-il sur le chemin du retour ?", "reponse": "Il commence à pleuvoir"}, {"question": "Comment rentrent-ils ?", "reponse": "Trempés mais heureux"}]}], "instructions": "Votre partenaire lit une courte histoire. Écoutez attentivement, puis répondez aux questions.", "consigne_partenaire": "Lisez l\'histoire une fois à voix haute. Posez ensuite les questions une par une."}' WHERE `id` = 28;
UPDATE `Exercices` SET `contenu` = '{"listes": [{"theme": "Choses à faire aujourd\'hui", "elements": ["appeler le médecin", "acheter du pain", "arroser les plantes", "rappeler Sophie", "prendre les médicaments", "sortir les poubelles"]}, {"theme": "Pays d\'Europe", "elements": ["France", "Allemagne", "Italie", "Espagne", "Portugal", "Belgique", "Suisse"]}, {"theme": "Animaux de la ferme", "elements": ["vache", "cochon", "mouton", "chèvre", "canard", "poule", "lapin", "cheval"]}, {"theme": "Objets de la salle de bain", "elements": ["savon", "serviette", "brosse à dents", "shampoing", "rasoir"]}, {"theme": "Métiers", "elements": ["médecin", "boulanger", "professeur", "pompier", "facteur", "infirmière"]}, {"theme": "Couleurs", "elements": ["rouge", "bleu", "jaune", "vert", "orange", "violet", "noir"]}], "instructions": "Votre partenaire vous lit une liste. Vous discutez d\'autre chose pendant 2 minutes, puis vous rappelez le maximum d\'éléments.", "consigne_partenaire": "Lisez la liste lentement. Pendant 2 minutes, parlez d\'autre chose. Demandez ensuite quels éléments ont été retenus."}' WHERE `id` = 29;

-- ================================================================
-- Vérification post-migration :
--   SELECT COUNT(*) FROM Exercices;              -- doit être 85
--   SHOW COLUMNS FROM Revisions LIKE 'stabilite'; -- doit exister
-- ================================================================
